"""Default form schema, derived from the legacy desktop application's config/form_schema.json."""
from __future__ import annotations

DEFAULT_FORM_SCHEMA: dict = {
    "form_name": "IT Request Form",
    "request_types": [
        "New Hire",
        "Termination",
        "Promotion",
        "Rehire",
        "New Shared Mailbox",
        "New Distribution Group",
    ],
    "fields": [
        {"id": "effective_date", "label": "Effective Date", "type": "date", "required": True,
         "description": "Date the change becomes active."},
        {"id": "name", "label": "Name", "type": "text", "required": True,
         "description": "Employee full legal name."},
        {"id": "cell_phone", "label": "Cell Phone", "type": "text", "required": False,
         "description": "Employee mobile number."},
        {"id": "address", "label": "Address", "type": "text", "required": False,
         "description": "Employee home address."},
        {"id": "property", "label": "Property", "type": "text", "required": False,
         "description": "Property/site assignment."},
        {"id": "department", "label": "Department", "type": "text", "required": True,
         "description": "Business unit or department."},
        {"id": "sub_department", "label": "Sub-Department", "type": "text", "required": False,
         "description": "Team or sub-group inside department."},
        {"id": "title", "label": "Title", "type": "text", "required": True,
         "description": "Job title."},
        {"id": "manager", "label": "Manager", "type": "text", "required": True,
         "description": "Direct manager name."},
    ],
    "groups": [
        {"id": "system_web", "title": "System / Web Access", "enabled": True,
         "items": [{"id": "vpn_access", "label": "VPN Access",
                    "description": "Enable or disable VPN access."}]},
        {"id": "email_groups", "title": "Email Groups", "enabled": True,
         "items": [{"id": "everyone", "label": "everyone@yourdomain.com",
                    "description": "Add/remove this email group."}]},
        {"id": "shared_mailbox", "title": "Shared Mailbox", "enabled": True,
         "items": [{"id": "shared_mailbox_access", "label": "Shared Mailbox Access",
                    "description": "Enable or disable shared mailbox access."}]},
        {"id": "sharepoint_sites", "title": "SharePoint Sites", "enabled": True,
         "items": [{"id": "sharepoint_site_access", "label": "SharePoint Site Access",
                    "description": "Enable or disable SharePoint site access."}]},
        {"id": "google_drives", "title": "Google Drives", "enabled": True,
         "items": [{"id": "google_drive_access", "label": "Google Drive Access",
                    "description": "Enable or disable Google Drive access."}]},
        {"id": "printer_access", "title": "Printer Access", "enabled": True,
         "items": [{"id": "printer_access", "label": "Printer Access",
                    "description": "Enable or disable printer access."}]},
    ],
}
