"""Default form schema, derived from the legacy desktop application's config/form_schema.json."""
from __future__ import annotations

DEFAULT_FORM_SCHEMA: dict = {
    "form_name": "IT Request Form",
    "request_types": [
        "New Hire",
        "Promotion",
        "Rehire",
        "Termination",
        "New Shared Mailbox",
        "New Distribution Group",
    ],
    "lookup_request_types": ["Promotion", "Rehire", "Termination"],  # legacy; ignored by current renderer
    "termination_request_types": ["Termination"],  # legacy; ignored by current renderer
    "fields": [
        {"id": "effective_date", "label": "Effective Date", "type": "date", "required": True,
         "description": "Date the change becomes active."},
        {"id": "name", "label": "Name", "type": "text", "required": True,
         "role": "employee_name",
         "description": "Employee full legal name."},
        {"id": "work_email", "label": "Work Email", "type": "email", "required": False,
         "role": "employee_email",
         "description": "Employee work email address (used to look up the employee on Promotion / Termination / Rehire)."},
        {"id": "cell_phone", "label": "Cell Phone", "type": "text", "required": False,
         "description": "Employee mobile number."},
        {"id": "property", "label": "Property", "type": "resource", "resource_kind": "property", "required": False,
         "description": "Property/site assignment. Pick from your Resources catalog; the address auto-fills below."},
        {"id": "address", "label": "Property Address", "type": "text", "required": False,
         "auto_from": {"source_field_id": "property", "attribute": "address"},
         "description": "Auto-filled from the selected property."},
        {"id": "department", "label": "Department", "type": "text", "required": True,
         "description": "Business unit or department."},
        {"id": "sub_department", "label": "Sub-Department", "type": "text", "required": False,
         "description": "Team or sub-group inside department."},
        {"id": "title", "label": "Title", "type": "text", "required": True,
         "description": "Job title."},
        {"id": "manager", "label": "Manager", "type": "text", "required": True,
         "description": "Direct manager name."},
        {"id": "forward_email_to", "label": "Forward Email To", "type": "text", "required": False,
         "role": "forward_email_to",
         "visible_when_request_type_in": ["Termination"],
         "description": "On Termination: another employee's email to forward this user's mail to."},
        {"id": "grant_full_access_to", "label": "Grant Full Mailbox Access To", "type": "text", "required": False,
         "role": "grant_full_access_to",
         "visible_when_request_type_in": ["Termination"],
         "description": "On Termination: another employee who should be granted full mailbox access."},
    ],
    "groups": [
        {"id": "system_web", "title": "System / Web Access", "enabled": True,
         "items": [{"id": "vpn_access", "label": "VPN Access",
                    "description": "Enable or disable VPN access."}]},
        {"id": "email_groups", "title": "Email Groups", "enabled": True,
         "items": [{"id": "everyone", "label": "everyone@yourdomain.com",
                    "description": "Add/remove this email group."}]},
        {"id": "shared_mailbox", "title": "Shared Mailbox", "enabled": True,
         "items": [{"id": "shared_mailbox_access", "label": "Shared Mailbox Access",
                    "description": "Enable or disable shared mailbox access."}]},
        {"id": "sharepoint_sites", "title": "SharePoint Sites", "enabled": True,
         "items": [{"id": "sharepoint_site_access", "label": "SharePoint Site Access",
                    "description": "Enable or disable SharePoint site access."}]},
        {"id": "google_drives", "title": "Google Drives", "enabled": True,
         "items": [{"id": "google_drive_access", "label": "Google Drive Access",
                    "description": "Enable or disable Google Drive access."}]},
        {"id": "printer_access", "title": "Printer Access", "enabled": True,
         "items": [{"id": "printer_access", "label": "Printer Access",
                    "description": "Enable or disable printer access."}]},
    ],
}
